name: 'Swagger CLI Build release'

on: push

jobs:

  build-and-push-image:
    name: 'Build Swagger CLI docker image and push it to dockerhub'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v2

      - name: 'build the image'
        run: |
          make GIT_REPOSITORY=${GITHUB_REPOSITORY} \
          GIT_SHA=${GITHUB_SHA} \
          GIT_SHORT_SHA=${GITHUB_SHA::7} \
          GIT_SHORT_SHA=${GITHUB_SHA::7} \
          GIT_BRANCH=${GITHUB_REF} \
          build-image

      - name: 'authenticate on docker hub'
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: 'push the image'
        run: make publish-image
